
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maluv
 */

public class Interface extends javax.swing.JFrame {
    ArrayList<Funcionario> ListaFunc;
    String gender;
    int age;
    int aux = 0;
    double soma_idade;
    double total_func, func_m, func_h;
    double total_func_porc, func_m_porc, func_h_porc, idade_media, idade_aux, idade_m, idade_h, idade_h_porc, idade_m_porc;

    
    public void LoadTabledFunc() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Funcionários", "Dia", "Mês", "Ano", "Sexo", "Idade"}, 0);

        for (int i = 0; i < ListaFunc.size(); i++) {
            Object linha[] = new Object[] {ListaFunc.get(i).getName(), ListaFunc.get(i).getBirthDay(),
                                           ListaFunc.get(i).getBirthMonth(), ListaFunc.get(i).getBirthYear(),
                                           ListaFunc.get(i).getGender(), ListaFunc.get(i).getAge()};
            modelo.addRow(linha);
        }

        tbl_func_infos.setModel(modelo);
    }

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        setLocationRelativeTo(null);
        ListaFunc = new ArrayList();
        button_salvar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        r_workers_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        r_workers_birthd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        r_workers_birthm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        r_workers_birthy = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        button_salvar = new javax.swing.JButton();
        female_option = new javax.swing.JRadioButton();
        male_option = new javax.swing.JRadioButton();
        other_option = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_func_infos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_func_relatorio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro do funcionário\n"));

        jLabel1.setText("Nome:");

        r_workers_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_workers_nameActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de nascimento: ");

        r_workers_birthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_workers_birthdActionPerformed(evt);
            }
        });

        jLabel3.setText("/");

        r_workers_birthm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_workers_birthmActionPerformed(evt);
            }
        });

        jLabel4.setText("/");

        r_workers_birthy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_workers_birthyActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo:");

        button_salvar.setText("Salvar");
        button_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_salvarActionPerformed(evt);
            }
        });

        buttonGroup1.add(female_option);
        female_option.setText("Feminino");
        female_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_optionActionPerformed(evt);
            }
        });

        buttonGroup1.add(male_option);
        male_option.setText("Masculino");
        male_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_optionActionPerformed(evt);
            }
        });

        buttonGroup1.add(other_option);
        other_option.setText("Outro");
        other_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                other_optionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(r_workers_name, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(female_option, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(male_option, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(other_option, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(r_workers_birthd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(r_workers_birthm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(r_workers_birthy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(button_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(r_workers_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(r_workers_birthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(r_workers_birthm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(r_workers_birthy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(female_option)
                    .addComponent(male_option)
                    .addComponent(other_option))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_salvar)
                .addGap(26, 26, 26))
        );

        tbl_func_infos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Dia", "Mês", "Ano", "Sexo", "Idade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_func_infos);
        if (tbl_func_infos.getColumnModel().getColumnCount() > 0) {
            tbl_func_infos.getColumnModel().getColumn(0).setResizable(false);
            tbl_func_infos.getColumnModel().getColumn(0).setHeaderValue("Nome");
            tbl_func_infos.getColumnModel().getColumn(1).setResizable(false);
            tbl_func_infos.getColumnModel().getColumn(1).setHeaderValue("Dia");
            tbl_func_infos.getColumnModel().getColumn(2).setResizable(false);
            tbl_func_infos.getColumnModel().getColumn(2).setHeaderValue("Mês");
            tbl_func_infos.getColumnModel().getColumn(3).setResizable(false);
            tbl_func_infos.getColumnModel().getColumn(3).setHeaderValue("Ano");
            tbl_func_infos.getColumnModel().getColumn(4).setResizable(false);
            tbl_func_infos.getColumnModel().getColumn(4).setHeaderValue("Sexo");
            tbl_func_infos.getColumnModel().getColumn(5).setResizable(false);
            tbl_func_infos.getColumnModel().getColumn(5).setHeaderValue("Idade");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        tbl_func_relatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Funcionários", "Porcentagem ", "Funcionárias M", "nuFuncionários H", "Idade Média", "Idade Feminina", "Idade Masculina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_func_relatorio);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void other_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_other_optionActionPerformed
        gender = "Outro";
    }//GEN-LAST:event_other_optionActionPerformed

    private void male_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_optionActionPerformed
        gender = "Masculino";
    }//GEN-LAST:event_male_optionActionPerformed

    private void female_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_optionActionPerformed
        gender = "Feminino";
    }//GEN-LAST:event_female_optionActionPerformed

    public int workersAge() {
        Date date = new Date();
        LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int ano_atual  = localDate.getYear();
        int mes_atual = localDate.getMonthValue();
        int dia_atual   = localDate.getDayOfMonth();
        int dia = Integer.parseInt(r_workers_birthd.getText());
        int mes = Integer.parseInt(r_workers_birthm.getText());
        int ano = Integer.parseInt(r_workers_birthy.getText());

        age = ano_atual - ano;

        if (mes_atual > mes) {
            age = age;

            if (dia_atual > dia) {
                age = age;
            } else {
                age = age - 1;
            }
        } else {
            age = age - 1;
        }
        
        return age;
    }

    private void button_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_salvarActionPerformed
        int dia = Integer.parseInt(r_workers_birthd.getText());
        int mes = Integer.parseInt(r_workers_birthm.getText());
        int ano = Integer.parseInt(r_workers_birthy.getText());

        Funcionario f = new Funcionario(r_workers_name.getText(), ano, dia, mes, gender, workersAge());
        ListaFunc.add(f);
        total_func++;
        LoadTabledFunc();

        idade_aux = workersAge();

        soma_idade = soma_idade + idade_aux;

        if (gender.equals("Feminino")) {
            func_m++;
            idade_m = idade_m + workersAge();
        }
        if (gender.equals("Masculino")) {
            func_h++;
            idade_h = idade_h + workersAge();
        }

        total_func_porc = total_func/total_func;
        func_m_porc = func_m/total_func;
        func_h_porc = func_h/total_func;
        idade_media = (soma_idade)/(total_func);
        idade_m_porc = idade_m/func_m;
        idade_h_porc = idade_h/func_h;
        aux++;


        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Funcionários", "Porcentagem ", "Funcionárias M", "Funcionários H", "Idade Média", "Idade Feminina", "Idade Masculina"}, 0);

        Object[] linha = {total_func, total_func_porc, func_m_porc, func_h_porc, idade_media, idade_m_porc, idade_h_porc};
        modelo.addRow(linha);

        tbl_func_relatorio.setModel(modelo);
    }//GEN-LAST:event_button_salvarActionPerformed

    private void r_workers_birthyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_workers_birthyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_workers_birthyActionPerformed

    private void r_workers_birthmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_workers_birthmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_workers_birthmActionPerformed

    private void r_workers_birthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_workers_birthdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_workers_birthdActionPerformed

    private void r_workers_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_workers_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_workers_nameActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_salvar;
    private javax.swing.JRadioButton female_option;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton male_option;
    private javax.swing.JRadioButton other_option;
    private javax.swing.JTextField r_workers_birthd;
    private javax.swing.JTextField r_workers_birthm;
    private javax.swing.JTextField r_workers_birthy;
    private javax.swing.JTextField r_workers_name;
    private javax.swing.JTable tbl_func_infos;
    private javax.swing.JTable tbl_func_relatorio;
    // End of variables declaration//GEN-END:variables
}
